version: '3.7'

services:
  portainer:
    container_name: DO__portainer
    networks:
      - traefik
      - default
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.202102__portainer.entrypoints=websecure
      - traefik.http.routers.202102__portainer.rule=Host(`portainer.nas.hyeon.pro`)
      - traefik.http.routers.202102__portainer.tls.certresolver=leresolver
      - traefik.http.services.202102__portainer.loadbalancer.server.port=9000

########################### NETWORKS
networks:
  traefik:
    external:
      name: traefik_proxy
