version: '3.7'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
  app:
    image: portainer/portainer:1.24.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        ## HTTP Routers
        - traefik.http.routers.202102__portainer.entrypoints=websecure
        - traefik.http.routers.202102__portainer.rule=Host(`portainer.nas.hyeon.pro`)
        - traefik.http.routers.202102__portainer.tls.certresolver=leresolver
        - traefik.http.services.202102__portainer.loadbalancer.server.port=9000
        
########################### NETWORKS
networks:
  agent_network:
    driver: overlay
    attachable: true
  default:
    external: 
      name: proxy-main

########################### VOLUMES
volumes:
  portainer_data: